name: Automatic deploy

on:
  workflow_call:
    inputs:
      PREFIX_NAMESPACE:
        required: true
        type: string
    secrets:
      GH_PRIVATE_TOKEN:
        required: true
      GATEKEEPER_HELM_API_KEY:
        required: true

env:
  GATEKEEPER_CLIENT_ID: 'dev-fullstack-helm'
  CLUSTER: 'DEV'

jobs:
  deploy-app:
    strategy:
      matrix:
        namespace: ['${{ inputs.PREFIX_NAMESPACE }}-devl', '${{ inputs.PREFIX_NAMESPACE }}-acpt', '${{ inputs.PREFIX_NAMESPACE }}-pprd']
      max-parallel: 10
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Github event
        run: cat ${GITHUB_EVENT_PATH}

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF }}

      - name: Checkout private actions
        uses: actions/checkout@v3
        with:
          repository: lacapitale/github-actions-private
          token: ${{ secrets.GH_PRIVATE_TOKEN }}
          path: ./.github/github-actions-private

      - name: Deploy
        uses: ./.github/github-actions-private/gatekeeper-helm
        with:
          gatekeeper-client-id: '${{ env.GATEKEEPER_CLIENT_ID }}'
          gatekeeper-api-key: ${{ secrets.GATEKEEPER_HELM_API_KEY }}
          helm-release-name: '${{ github.event.repository.name }}'
          helm-namespace: '${{ matrix.namespace }}'
          helm-values: 'values/${{ matrix.namespace }}.yaml'
          helm-chart-repo-run-dir: './chart'
          gke-cluster: '${{ env.CLUSTER }}'
