name: CI

on:
  workflow_call:
    inputs:
      node-version:
        required: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # Timeout in minutes

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Tests
        run: npm run test

      - name: Audit
        run: npm audit
