name: Manual deploy

on:
  workflow_call:
    inputs:
      NAMESPACE:
        required: true
        type: string

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Github event
        run: cat ${GITHUB_EVENT_PATH}

      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF }}

      - name: Set development env
        if: contains(inputs.NAMESPACE, 'prod') != true
        run: |
          echo "CLUSTER=DEV" >> $GITHUB_ENV
          echo "GATEKEEPER_CLIENT_ID=dev-fullstack-helm" >> $GITHUB_ENV
          echo "GATEKEEPER_HELM_API_KEY=${{ secrets.GATEKEEPER_HELM_API_KEY }}" >> $GITHUB_ENV

      - name: Set prod env
        if: contains(inputs.NAMESPACE, 'prod')
        run: |
          echo "CLUSTER=PROD" >> $GITHUB_ENV
          echo "GATEKEEPER_CLIENT_ID=prod-fullstack-helm" >> $GITHUB_ENV
          echo "GATEKEEPER_HELM_API_KEY=${{ secrets.GATEKEEPER_HELM_API_KEY_PROD }}" >> $GITHUB_ENV

      - name: Checkout private actions
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PRIVATE_TOKEN }}
          repository: lacapitale/github-actions-private
          path: ./.github/github-actions-private

      - name: Deploy
        uses: ./.github/github-actions-private/gatekeeper-helm
        with:
          gatekeeper-client-id: '${{ env.GATEKEEPER_CLIENT_ID }}'
          gatekeeper-api-key: '${{ env.GATEKEEPER_HELM_API_KEY }}'
          helm-release-name: '${{ github.event.repository.name }}'
          helm-namespace: '${{ inputs.NAMESPACE }}'
          helm-values: 'values/${{ inputs.NAMESPACE }}.yaml'
          helm-chart-repo-run-dir: './chart'
          gke-cluster: '${{ env.CLUSTER }}'
