name: nodeJS scan

on:
  workflow_call:

jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan check
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF }}

      - name: njsscan
        id: njsscan
        uses: ajinabraham/njsscan-action@v6
        with:
          args: '.'
