name: Npm audit fix

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # Timeout in minutes
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF }}

      - name: Use Node.js ${{ inputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Create audit fix pr
        uses: ybiquitous/npm-audit-fix-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'chore/npm-audit-fix'
          default_branch: ${{ github.event.repository.default_branch }}
          commit_title: 'NPM audit fix'
          labels: 'chore'
