name: Update package

on:
  workflow_call:

jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
      - name: set remote url
        run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      
      - name: package-update
        uses: taichi/actions-package-update@v0.7.2
        env:
          AUTHOR_EMAIL: fullstack.bot@lacapitale.com
          AUTHOR_NAME: Team FullStack's bot
          EXECUTE: 'true'
          GITHUB_TOKEN: ${{ secrets.GH_PRIVATE_TOKEN }}
          LOG_LEVEL: debug
        with:
          args: -u --packageFile package.json --loglevel verbose
