name: Update package

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string
      BUILD_COMMAND:
        required: false
        type: string
        default: npm run build
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF }}

      - name: set remote url
        run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      
      - name: package update
        uses: taichi/actions-package-update@v0.7.2
        env:
          AUTHOR_EMAIL: fullstack.bot@lacapitale.com
          AUTHOR_NAME: Team FullStack's bot
          EXECUTE: 'true'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: chore/
          UPDATE_COMMAND: npm
        with:
          args: update

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: ${{ inputs.BUILD_COMMAND }}
