name: PR Labeler

on:
  workflow_call:
    inputs:
      CONFIGURATION_PATH:
        required: false
        type: string
        default: .github/pr-labeler.yaml

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: ${{ inputs.CONFIGURATION_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
