name: PR Labeler

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
