name: CI on Push (Sentry)

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string
      URL_PREFIX:
        required: true
        type: string
      SENTRY_PROJECT_NAME:
        required: true
        type: string
      BUILD_COMMAND:
        required: false
        type: string
        default: npm run build:prodfr
    secrets:
      SENTRY_AUTH_TOKEN:
        required: true

jobs:
  sentry:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # Timeout in minutes

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF }}

      - name: Use Node.js ${{ inputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Get package.json version for CI
        run: echo "PACKAGE_VERSION=$(grep '"version"' package.json | cut -d '"' -f 4)" >> $GITHUB_ENV

      - name: Build
        run: ${{ inputs.BUILD_COMMAND }}

      - name: Setup Sentry CLI
        uses: mathrix-education/setup-sentry-cli@1.2.0
        with:
          version: latest
          token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          organization: la-capitale-assureur-de-ladmin
          project: ${{ inputs.SENTRY_PROJECT_NAME }}

      - name: Create new release
        run: sentry-cli releases new $PACKAGE_VERSION
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
      
      - name: Upload sourcemaps to Sentry
        run: sentry-cli releases files $PACKAGE_VERSION upload-sourcemaps ./dist --url-prefix '${{ inputs.URL_PREFIX }}' --validate
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
      
      - name: Finalize release version to Sentry
        run: sentry-cli releases finalize $PACKAGE_VERSION
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
  #     #sentry-cli releases set-commits --auto $PACKAGE_VERSION
